### ISSUE TITLE
Sprint 1: Sign-off && Feedback

### ISSUE THREAD

**Issue by zisding** [aiatro/k9-mail-390#14]
Sprint 1 is incomplete due to the following reason,
1.  The CI is not set up correctly yet, as I said in the meeting, we need to run two Gradle tasks, build and test, simply running testDebug is not enough.  I showed your team members how to run these two commands and how to display all the tasks in the Gradle, but you still don't change it. 

**Notes:**

1. Well done on the wiki, documentation!
2. Make sure your CI is running the tests.
3. The “support for mailing lists” sounds pretty good. I think you can work on it. 
4. Do some planning before going forward, just make sure to add priority to them and estimated time for the tasks. For the detailed functions, you can discuss with your team members, but keep in mind, every team member should contribute to the project (the email I sent you yesterday). Also, you can check the example.

**Comment by aiatro** [comment]
@zisding , The updates to the gradle file are already there, they just haven't been merged with master yet. In our CI environment the tests pass and the build succeeds. I'll create a pull request or use my admin privileges to forcibly merge it.
