### ISSUE TITLE
Complete k9 architecture

### ISSUE THREAD

**Issue by nirmal864** [aiatro/k9-mail-390#2]
As a developer, I would like to understand the k9 mail architecture and its main components

  Include architecture in Wiki and Google docs (for TA)

[Story Points: 3]
[Risk: Low]
[Priority: High]

**Comment by ShawnGuerra-Bautista** [comment]
Someone willing to create the google docs?

Anyway, unfortunately, the architecture will be quite challenging to create; it's not as simple as generating the UML diagram. I tried using SciTool Understand, but the diagrams were too large and many files are coupled. It's literally unreadable. I tried separating the modules while only focusing on the source code (k9mail, k9mail-library, openpgp-api, and HoloColoPicker), but, even then, each module has lots of coupling and components.

So, my suggestion is that we focus on recovering the architecture for the main module, k9mail, first. Particularly, the 'activity' package which contains the functionality of the system is of strong interest. We can discuss of our further observations through our dedicated channel or by using google docs. We can also create UML diagrams for files in the 'activity' package.

**Comment by aiatro** [comment]
I'll create the docs and send you all the links

**Comment by aiatro** [comment]
To look over the architecture we should mainly stick to analyzing the code in the k9 mail package as the rest are just libraries to help it operate. There's too much coupling to use the diagrams to understand it. We should go from code to architecture, not the other way around.

**Comment by ShawnGuerra-Bautista** [comment]
You're right.

My suggestion was that we should just focus on analyzing the code of the main module, k9mail. To be more specific, the 'activity' package is of interest for us and we can generate the diagram/architecture of the software from that.

**Comment by refatK** [comment]
Architectural information has been added on the wiki,
https://github.com/aiatro/k9-mail-390/wiki/Potential-Features

**Comment by aiatro** [comment]
I've added the last of the diagrams (class, module and package view) to the appropriate section in the wiki.
