### ISSUE TITLE
List of stories 

### ISSUE THREAD

**Issue by nirmal864** [aiatro/k9-mail-390#3]
As a user, I would like to suggest features/stories to implement in the app

- Come up with a list of user stories and choose one basic feature to implement for Sprint 2 

[Story Points: 1]
[Risk: Low]
[Priority: High]

**Comment by refatK** [comment]
We have listed potential features on the wiki here:

https://github.com/aiatro/k9-mail-390/wiki/Potential-Features

**Comment by aiatro** [comment]
It has been decided that we shall pursue the mailing list feature as detailed in #11
